### ISSUE TITLE
Drop dependency on SDK in favour of Runtime

### ISSUE THREAD

**Issue by virzak** [dotnet/format#1159]
The following code requires that certain SDK is installed to use the tool:

https://github.com/dotnet/format/blob/a1bce0d22a9cbf3299a16e68ec2a0a494aa28345/src/Program.cs#L136-L140

However, it is only the [Runtime](https://docs.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues#runtime-not-found) that's required to be present for `dotnet tool`

For some context of the issue:

After switching to .Net 6 preview 4 and C# 10 in order to utilize `global using` statements, the build server, which installed .Net 6, also needed .Net 5. Installing SDK takes longer than installing the runtime.

Here is the Azure Pipline code which should be enough, but isn't:

```yaml
- task: UseDotNet@2
  displayName: 'Use .NET 5 Runtime'
  inputs:
    version: '5.x'
    packageType: runtime

- task: UseDotNet@2
  displayName: 'Use .NET 6 Preview SDK'
  inputs:
    version: '6.x'
    includePreviewVersions: true

```
