### ISSUE TITLE
Logging warnings to stderr causes pipeline to fail

### ISSUE THREAD

**Issue by larkworthy** [dotnet/format#1205]
We use a step in our Azure DevOps pipeline to run dotnet-format. It's run as a command-line step that fails when there is output on stderr. This is the step:

```
  steps:
  - task: CmdLine@2
    inputs:
      script: '"$(dotnet-format)" --check --verbosity diagnostic'
      failOnStderr: true
```

The change to [Log warnings and errors to the standard error stream (982)](https://github.com/dotnet/format/pull/982) in the latest release causes the pipeline to fail on warnings.

Is it possible to have an option to only write errors to stderr? Or, are there other options to support format validation in a pipeline?
