### ISSUE TITLE
pre-commit hook does not work if the solution is in a sub directory

### ISSUE THREAD

**Issue by FrancisGauthier** [dotnet/format#1232]
i use the following .pre-commit-config.yaml file.

![image](https://user-images.githubusercontent.com/1427117/126219511-2b0f57f5-da56-4a4c-b6be-3ef387950dd7.png)

The structure on the repository looks like this
repo
   src
      solution.sln
   .pre-commit-config.yaml
   
 The original repo used to pass solutions from a subdirectory.  Looks like it is not possible to pass the solution in an argument with this hook.  I get the following error saying that there is no solution found in the directory
   
![image](https://user-images.githubusercontent.com/1427117/126219828-3dbe7ab3-a551-477d-9da4-d4f183090a67.png)

Thanks,

**Comment by tcharetteacerta** [comment]
Seconded. This is still the case.

**Comment by ylatuya** [comment]
You can pass the path to the solution using the `entry` arguments,  modifying the `dotnet format` command to your needs:

```
-   repo: local
    hooks:
    #Use dotnet format already installed on your machine
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format src/solution.sln -v normal --include
        files: ^src/.*
        types_or: ["c#", "vb"]
```

I case you have several solutions in your repository, you can add several hooks with the `files` filter, each one running against a particular solution file

```
-   repo: local
    hooks:
    #Use dotnet format already installed on your machine
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format src/project1/solution.sln -v normal --include
        files: ^src/project1/.*
        types_or: ["c#", "vb"]
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format src/project2/solution.sln -v normal --include
        files: ^src/project2/.*
        types_or: ["c#", "vb"]
```

This way files from `src/project1/` will be checked with `dotnet format src/project1/solution.sln` and files from `src/project2/` will be checked with `dotnet format src/project2/solution.sln`

```
$ git commit src/project1/MyApp/Test.cs
dotnet-format............................................................Passed
dotnet-format........................................(no files to check)Skipped
```
