### ISSUE TITLE
GitHub Action or GitHub App/Bot to Lint PRs

### ISSUE THREAD

**Issue by warrenbuckley** [dotnet/format#156]
Does the DotNet team have any plans of making this a GitHub Action or GitHub Bot?

As it would be good to have this available to lint PRs automatically for us with GitHub Checks API and highlight the items in the GitHub diff view of a PR with using the `dry-run` option

Where finally you could use the Checks API to Automatically fix the errors & do a commit on a users behalf if they choose that they want to correct it.

https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/#step-26-automatically-fixing-rubocop-errors

**Comment by ctolkien** [comment]
FYI @warrenbuckley , that was my rationale for https://github.com/dotnet/format/issues/90

I was going to have it automatically apply comments at the appriopriate line items with suggested fixes. Having it simple offer to fix all the things would be nicer!

**Comment by feliwir** [comment]
Would be interested in this aswell!

**Comment by casz** [comment]
Here is the workflow I am using for it:

```yml
name: DotNet

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - uses: actions/checkout@v2

      # workaround for dotnet tools not being on path https://github.com/actions/virtual-environments/issues/213
      - name: add .dotnet/tools to path
        run: echo "::set-env name=PATH::${PATH}:${HOME}/.dotnet/tools"

      - run: dotnet tool install -g dotnet-format

      - run: dotnet format --folder ./ --dry-run --check
```
