### ISSUE TITLE
dotnet format not working in Azure Pipelines

### ISSUE THREAD

**Issue by mykeels** [dotnet/format#568]
I have a pipeline with the following bash task:

```sh
dotnet tool install -g dotnet-format

ls -ah ~/

. ~/.bashrc
. ~/.profile

dotnet format --check --dry-run
```

It used to work beautifully, as the `. ~/.bashrc` would refresh the bash terminal session, making `dotnet format` available.

Now, it doesn't work anymore. And nothing's changed in the pipeline config.

I just get:

```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-format does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by JoeRobich** [comment]
@mykeels Sorry you are having issues. I am not sure anything from our end is responsible for this change in behavior. I can point you to a blog post I saw recently about running dotnet format from an azure pipeline, perhaps their method will work for you as well. Here is the article https://www.meziantou.net/enforce-dotnet-code-style-in-ci-with-dotnet-format.htm

**Comment by remcorakers** [comment]
@mykeels just as a reference, we use this step in our Azure DevOps pipeline to install dotnet format:
```
- task: DotNetCoreCLI@2
  displayName: "Install dotnet format"
  inputs:
    command: custom
    custom: tool
    arguments: install -g dotnet-format --version 3.2.107702 --ignore-failed-sources
```
